# NOTE:make sure you launch tmux and run `prefix+I` to initialize TPM
# 	this config designed for windows terminal -> SSH-Linux -> tmux/nvim

# Allow vim motions in copy-mode
setw -g mode-keys vi

# Secondary prefix for primary use
set -g prefix2 C-f
bind C-f send-prefix

# General options
set-option -w -g aggressive-resize on
get -g status-right "%a, %b %d"
set -g default-terminal "tmux-256color"

# Note: Plugin manager start
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# Note: #### START #### custom plugins
set -g @plugin 'theutz/tmux-tokyonight-nvim'
set -g @tokyonight 'moon'
# set-option -ga terminal-overrides ",xterm-256color:Tc" # old setting - may be useful later
set -as terminal-overrides ",*:Tc"

# Note: #### END #### custom plugins

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
